#server:
#  port: 9090

logging:
  level:
    root: INFO,ERROR

spring:
  application:
    name: back-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.49.95:3306/miniprogram?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
      hibernate:
        ddl-auto: update  # 不要用create，会删除表；都使用update，第一次会创建表，以后更新表
        show-sql: true
        format-sql: true
  redis:
    host: 47.100.49.95
    password:
    port: 6379
#  data:
#      rest:
#        base-path: /fuhai  # 此时REST资源的路径变成了http://localhost:9002/fuhai/workers